# Generated by Django 3.1.2 on 2022-03-30 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Care',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Care Date')),
                ('care', models.CharField(choices=[('W', 'Water'), ('F', 'Fertilizer')], default='W', max_length=1)),
            ],
        ),
    ]
