# Generated by Django 3.1.2 on 2022-03-31 00:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_auto_20220331_0016'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='pot',
        ),
        migrations.DeleteModel(
            name='Pot',
        ),
    ]
